stages:
  data_splitting:
    cmd: python model/train_val_test_split.py
    deps:
    - model/data/raw_data
    - model/train_val_test_split.py
    outs:
    - model/data/classes.txt
    - model/data/images
    - model/data/labels
  model_training:
    cmd: python yolov5/train.py --img 640 --batch 1 --epochs 100 --data model/dataset.yaml --weights yolov5s.pt --hyp model/hyp.scratch.yaml --device mps
    deps:
      - model/data/classes.txt
      - model/data/images
      - model/data/labels
    outs:
      - yolov5/runs/train/exp