name: Publish Docker image
on:
  push:
    branches:
    - 32-container-deployment-to-registry-on-merge

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image FishFinder API
        uses: docker/build-push-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: ghcr.io
          repository: alexpotv/fishfinder
          tags: FishFinderAPI:latest
          dockerfile: model_serving/api/Dockerfile


