name: Publish Docker image
on:
  push:
    branches:
    - 32-container-deployment-to-registry-on-merge

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./model_serving/api/Dockerfile
            image: FishFinderAPI

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image FishFinder API
        uses: docker/build-push-action@v1
        with:
          dockerfile: ${{ matrix.dockerfile }}
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
          repository: ${{ github.repository }}
          registry: ${{ env.REGISTRY }}

#      - name: Push to GitHub Packages
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          registry: ghcr.io
#          repository: alexpotv/fishfinder
#          image: FishFinderAPI
#          tags: latest
#          dockerfile: model_serving/api/Dockerfile
