name: DVC Pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/406343717543/locations/global/workloadIdentityPools/fishfinder-wip/providers/github-actions'
          service_account: 'github-runner@fishfinder-349617.iam.gserviceaccount.com'
      - name: Run DVC Pipeline
        run: |
          pip install -r requirements.txt
          dvc pull
          dvc repro
