name: DVC Pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.0'
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}
      - id: 'dvc'
        name: Run DVC Pipeline
        run: |
          pip install -r requirements.txt
          dvc pull
          dvc repro
