name: DVC Pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Run DVC Pipeline
        run: |
          pip install -r requirements.txt
          dvc pull
          dvc repro
