name: DVC Pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.0'
        with:
          workload_identity_provider: 'projects/406343717543/locations/global/workloadIdentityPools/fishfinder-github/providers/github-provider'
          service_account: 'fishfinder-github@fishfinder-349617.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud config set account 'fishfinder-github@fishfinder-349617.iam.gserviceaccount.com'
      - name: Run DVC Pipeline
        run: |
          echo ${GOOGLE_APPLICATION_CREDENTIALS}
          gcloud auth list
          gcloud components install alpha --quiet
          gcloud alpha storage ls gs://fish-finder-data
          dvc pull
