name: Tests - Model Serving
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: 'install_requirements'
        name: 'Install requirements'
        run: |
          pip install -r requirements.txt
      - id: 'run-pytest'
        name: 'Run PyTest'
        run: |
          python -m pytest
