version: '3'

services:

  api:
    container_name: flask_api
    restart: always
    image: ghcr.io/alexpotv/fishfinder/api:latest
    volumes: ['./api:/api']
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5002:5000"

  nginx:
    container_name: nginx
    restart: always
    image: ghcr.io/alexpotv/fishfinder/nginx:latest
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"

networks:
  apinetwork: